//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocios.EntityFramework
{
    using Negocios.ConexaoBD;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities(int pTimeOut = 30)
            : base(new TransacoesBD(pTimeOut, false).StringDeConexao<ConnectionString_EntityFramework>())
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DONATIVO> DONATIVO { get; set; }
        public virtual DbSet<ENTRADASDONATIVO> ENTRADASDONATIVO { get; set; }
        public virtual DbSet<RECIBO> RECIBO { get; set; }
        public virtual DbSet<TIPODONATIVO> TIPODONATIVO { get; set; }
        public virtual DbSet<TIPORECIBO> TIPORECIBO { get; set; }
    }
}
