//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocios.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONATIVO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONATIVO()
        {
            this.ENTRADASDONATIVO = new HashSet<ENTRADASDONATIVO>();
        }
    
        public int DONID { get; set; }
        public int DONTIPO { get; set; }
        public decimal DONVALOR { get; set; }
    
        public virtual TIPODONATIVO TIPODONATIVO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTRADASDONATIVO> ENTRADASDONATIVO { get; set; }
    }
}
