//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocios.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTRADASDONATIVO
    {
        public int ENTID { get; set; }
        public int ENTRECIBO { get; set; }
        public int ENTDONATIVO { get; set; }
    
        public virtual DONATIVO DONATIVO { get; set; }
        public virtual RECIBO RECIBO { get; set; }
    }
}
