//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocios.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIBO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECIBO()
        {
            this.ENTRADASDONATIVO = new HashSet<ENTRADASDONATIVO>();
        }
    
        public int RECID { get; set; }
        public decimal RECTOTAL { get; set; }
        public string RECASSINADOPOR { get; set; }
        public string RECCONFERIDOPOR { get; set; }
        public bool RECSEGUNDAVIA { get; set; }
        public int RECTIPODONATIVO { get; set; }
        public System.DateTime RECDATA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTRADASDONATIVO> ENTRADASDONATIVO { get; set; }
        public virtual TIPODONATIVO TIPODONATIVO { get; set; }
    }
}
