//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocios.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPORECIBO
    {
        public int TIPID { get; set; }
        public int TIPCOD { get; set; }
        public string TIPDESC { get; set; }
    }
}
